# Generated by Django 5.0.6 on 2024-06-30 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hechizo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('escuela', models.CharField(choices=[('Abjuración', 'Abjuración'), ('Conjuración', 'Conjuración'), ('Adivinación', 'Adivinación'), ('Encantamiento', 'Encantamiento'), ('Evocación', 'Evocación'), ('Transmutación', 'Transmutación')], max_length=20)),
                ('descriptor', models.CharField(blank=True, choices=[('Ácido', 'Ácido'), ('Aire', 'Aire'), ('Caótico', 'Caótico'), ('Frío', 'Frío'), ('Oscuridad', 'Oscuridad'), ('Muerte', 'Muerte'), ('Tierra', 'Tierra'), ('Electricidad', 'Electricidad'), ('Maligno', 'Maligno'), ('Miedo', 'Miedo'), ('Fuego', 'Fuego'), ('Fuerza', 'Fuerza'), ('Maligno', 'Maligno'), ('Dependiente del Lenguaje', 'Dependiente del Lenguaje'), ('Legal', 'Legal'), ('Luz', 'Luz'), ('Afecta la Mente', 'Afecta la Mente'), ('Sónico', 'Sónico'), ('Agua', 'Agua')], max_length=30, null=True)),
                ('nivel', models.IntegerField()),
                ('componentes', models.CharField(choices=[('V', 'V'), ('S', 'S'), ('M', 'M'), ('F', 'F'), ('DF', 'DF'), ('XP', 'XP')], max_length=50)),
                ('tiempo_de_lanzamiento', models.CharField(max_length=50)),
                ('rango', models.CharField(choices=[('Personal', 'Personal'), ('Toque', 'Toque'), ('Cerca', 'Cerca'), ('Medio', 'Medio'), ('Lejos', 'Lejos'), ('Ilimitado', 'Ilimitado'), ('Otro', 'Otro')], max_length=20)),
                ('objetivo', models.CharField(max_length=100)),
                ('efecto', models.CharField(max_length=100)),
                ('duracion', models.CharField(max_length=50)),
                ('tirada_de_salvacion', models.CharField(max_length=100)),
                ('resistencia_de_hechizos', models.CharField(max_length=100)),
                ('descripcion_completa', models.TextField()),
            ],
            options={
                'verbose_name': 'Hechizo',
                'verbose_name_plural': 'Hechizos',
            },
        ),
    ]
