# Generated by Django 5.0.6 on 2024-06-30 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CalculatorApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hechizo',
            name='componentes',
            field=models.CharField(max_length=100),
        ),
    ]
