# Generated by Django 5.0.6 on 2024-06-30 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CalculatorApp', '0002_alter_hechizo_componentes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hechizo',
            name='componentes',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hechizo',
            name='descripcion_completa',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hechizo',
            name='duracion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hechizo',
            name='efecto',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hechizo',
            name='nivel',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hechizo',
            name='objetivo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hechizo',
            name='rango',
            field=models.CharField(blank=True, choices=[('Personal', 'Personal'), ('Toque', 'Toque'), ('Cerca', 'Cerca'), ('Medio', 'Medio'), ('Lejos', 'Lejos'), ('Ilimitado', 'Ilimitado'), ('Otro', 'Otro')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='hechizo',
            name='resistencia_de_hechizos',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hechizo',
            name='tiempo_de_lanzamiento',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hechizo',
            name='tirada_de_salvacion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
