# Generated by Django 5.0.6 on 2024-06-30 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CalculatorApp', '0003_alter_hechizo_componentes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hechizo',
            name='clase',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
