# Generated by Django 5.0.6 on 2024-07-01 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CalculatorApp', '0004_hechizo_clase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hechizo',
            name='clase',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hechizo',
            name='descriptor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hechizo',
            name='escuela',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hechizo',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hechizo',
            name='rango',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
