# Generated by Django 5.0.6 on 2024-07-03 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CalculatorApp', '0005_alter_hechizo_clase_alter_hechizo_descriptor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hechizo',
            name='subescuela',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
