# Generated by Django 5.0.6 on 2024-08-09 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CalculatorApp', '0007_hechizo_descripcion_corta'),
    ]

    operations = [
        migrations.AddField(
            model_name='hechizo',
            name='clases',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='hechizo',
            name='nivel',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
