# Generated by Django 5.0.6 on 2024-08-09 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CalculatorApp', '0009_rename_nivel_hechizo_clase_nivel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hechizo',
            name='clase',
        ),
    ]
