# Generated by Django 5.0.6 on 2024-08-10 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CalculatorApp', '0010_remove_hechizo_clase'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenHechizo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='hechizos/imagenes/')),
                ('hechizo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='CalculatorApp.hechizo')),
            ],
            options={
                'verbose_name': 'Imagen del Hechizo',
                'verbose_name_plural': 'Imágenes del Hechizo',
            },
        ),
    ]
