# Generated by Django 5.0.6 on 2024-08-10 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CalculatorApp', '0011_imagenhechizo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImagenHechizo',
        ),
    ]
