# Generated by Django 5.0.6 on 2024-08-10 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CalculatorApp', '0012_delete_imagenhechizo'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpellImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.ImageField(upload_to='images/spells/')),
            ],
        ),
        migrations.AddField(
            model_name='hechizo',
            name='imagenes',
            field=models.ManyToManyField(blank=True, to='CalculatorApp.spellimage'),
        ),
    ]
