# Generated by Django 5.0.6 on 2024-08-10 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CalculatorApp', '0014_remove_hechizo_imagenes_delete_spellimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpellImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='images/spell_images')),
                ('hechizo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spell_images', to='CalculatorApp.hechizo')),
            ],
            options={
                'verbose_name': 'Imagen de Hechizo',
                'verbose_name_plural': 'Imágenes de Hechizos',
            },
        ),
    ]
