# Generated by Django 5.0.6 on 2024-08-10 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CalculatorApp', '0015_spellimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='hechizo',
            name='imagen_1',
            field=models.ImageField(blank=True, null=True, upload_to='images/spell_images/'),
        ),
        migrations.AddField(
            model_name='hechizo',
            name='imagen_2',
            field=models.ImageField(blank=True, null=True, upload_to='images/spell_images/'),
        ),
        migrations.AddField(
            model_name='hechizo',
            name='imagen_3',
            field=models.ImageField(blank=True, null=True, upload_to='images/spell_images/'),
        ),
        migrations.AddField(
            model_name='hechizo',
            name='imagen_4',
            field=models.ImageField(blank=True, null=True, upload_to='images/spell_images/'),
        ),
        migrations.DeleteModel(
            name='SpellImage',
        ),
    ]
