# Generated by Django 5.0.6 on 2024-08-11 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CalculatorApp', '0016_hechizo_imagen_1_hechizo_imagen_2_hechizo_imagen_3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hechizo',
            name='componentes',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='hechizo',
            name='descripcion_corta',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='hechizo',
            name='descriptor',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='hechizo',
            name='duracion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='hechizo',
            name='efecto',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='hechizo',
            name='escuela',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='hechizo',
            name='nombre',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='hechizo',
            name='objetivo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='hechizo',
            name='rango',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='hechizo',
            name='resistencia_de_hechizos',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='hechizo',
            name='subescuela',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='hechizo',
            name='tiempo_de_lanzamiento',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='hechizo',
            name='tirada_de_salvacion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
