# Generated by Django 5.0.6 on 2024-08-11 14:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CalculatorApp', '0018_listadefavoritos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ListaDeFavoritos',
            new_name='ListaFavoritos',
        ),
    ]
