# Generated by Django 5.0.6 on 2024-08-12 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CalculatorApp', '0019_rename_listadefavoritos_listafavoritos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listafavoritos',
            name='hechizos',
        ),
        migrations.AddField(
            model_name='listafavoritos',
            name='hechizos_ids',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
