# Generated by Django 5.0.6 on 2024-08-12 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CalculatorApp', '0020_remove_listafavoritos_hechizos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listafavoritos',
            name='descripcion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='listafavoritos',
            name='hechizos_ids',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='listafavoritos',
            name='nombre',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
