# Generated by Django 5.0.6 on 2024-08-13 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CalculatorApp', '0021_listafavoritos_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listafavoritos',
            name='clase',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
