# Generated by Django 5.0.6 on 2024-07-07 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Characters', '0003_deity_size_statistics_description_age_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavingThrow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strength', models.IntegerField(blank=True, null=True)),
                ('reflex', models.IntegerField(blank=True, null=True)),
                ('will', models.IntegerField(blank=True, null=True)),
                ('strength_base', models.IntegerField(blank=True, null=True)),
                ('reflex_base', models.IntegerField(blank=True, null=True)),
                ('will_base', models.IntegerField(blank=True, null=True)),
                ('strength_magic', models.IntegerField(blank=True, null=True)),
                ('reflex_magic', models.IntegerField(blank=True, null=True)),
                ('will_magic', models.IntegerField(blank=True, null=True)),
                ('strength_other', models.IntegerField(blank=True, null=True)),
                ('reflex_other', models.IntegerField(blank=True, null=True)),
                ('will_other', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='deity',
            name='info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='armour_class',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='charisma_mod',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='charisma_mod_temporal',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='constitution_mod',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='constitution_mod_temporal',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='dexterity_mod',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='dexterity_mod_temporal',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='grapple',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='initiative',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='intelligence_mod',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='intelligence_mod_temporal',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='strength_mod',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='strength_mod_temporal',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='wisdom_mod',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='wisdom_mod_temporal',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='saving_throws',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Characters.savingthrow'),
        ),
    ]
