# Generated by Django 5.0.6 on 2024-07-07 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Characters', '0006_abilities_character_user_statistics_reflex_temporal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abilities',
            name='class_bonus',
        ),
        migrations.RemoveField(
            model_name='abilities',
            name='modifier_rank',
        ),
        migrations.RemoveField(
            model_name='abilities',
            name='other_modifier',
        ),
        migrations.RemoveField(
            model_name='abilities',
            name='rank',
        ),
        migrations.RemoveField(
            model_name='abilities',
            name='sum',
        ),
        migrations.AlterField(
            model_name='abilities',
            name='basic',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='CharacterAbilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_bonus', models.BooleanField(default=False)),
                ('sum', models.IntegerField(blank=True, editable=False, null=True)),
                ('modifier_rank', models.IntegerField(blank=True, null=True)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('other_modifier', models.IntegerField(blank=True, null=True)),
                ('abilities', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Characters.abilities')),
                ('statistics', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Characters.statistics')),
            ],
        ),
        migrations.AlterField(
            model_name='character',
            name='abilities',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Characters.characterabilities'),
        ),
    ]
