# Generated by Django 5.0.6 on 2024-07-07 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Characters', '0007_remove_abilities_class_bonus_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='characterabilities',
            name='statistics',
        ),
    ]
